// SPDX-License-Identifier: MIT
// GENERATED by `cargo run --bin evm_export` from a real proof. Do not edit by hand.
pragma solidity ^0.8.20;

import "./Verifier.sol";

contract SolvencyVerifierDemo {
    event Verified(bool ok, uint256 gasUsed);

    // Verify the baked-in real proof on-chain; emits Verified(true, gas). No arguments.
    function verify() external returns (bool ok) {
        Verifier.VK memory vk = _vk();
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input) = _proof();
        uint256 g = gasleft();
        ok = Verifier.verify(a, b, c, input, vk);
        emit Verified(ok, g - gasleft());
    }

    function _vk() internal pure returns (Verifier.VK memory vk) {
        vk.alpha = [uint256(0x300ecaa2b2be9274c7309ccea414e40a020edc0ee30c0018b02729384a8666d2), 0x2ea6857108f11e0f12a146b8aae1be9de807d00398e297b022dc1f15342b55c4];
        vk.beta = [[uint256(0x0f33cbd1c285337deee042cd21732111a6cbf26a53149b2035066de17232ad5c), 0x0f1bf2755e3e3dfe754353d46e0399bb46ecc0b314e3742b63c0914b49171147], [uint256(0x17ac82384b7b9fd1dcebdfce162cb0f05a385468d84d73f9c2f34f724563413e), 0x07d8a155237e0087d2e2497efc5447d88733c58adf88d70a10180ad36190f642]];
        vk.gamma = [[uint256(0x20210c2211a9dcaef9b535ef5d9757438bffa5dfa0a09dc4c18f1904f4f4f562), 0x1d0bf62d4acc0a31fac5a860685b7df4ccc061ffd80667098591921d675b2b7f], [uint256(0x11a10bd7a79c7b1dac2a7d57ffa7df419fcc2dce61c0b2818245d3de9a65c4df), 0x111b3d13a9be944de00fe807d136829e1164f1584ac653feae2a3a50acca45d6]];
        vk.delta = [[uint256(0x0f4629ec3390f42bebe7f31ac5e17c55ef4d25bb4f712fc97584fd413181c130), 0x1a931688f3959bb627a7c0e35d6bc5299cc1bda0c0589cae2d495cd58bfc6db2], [uint256(0x1e5c5392730e68a7607b6d60a8b9f060017f3b27f81447ad64f1b5bfeaf8a00c), 0x0f13315d39ab24ad5a18a65a40af2ef0210f413bf48f89837c6b46dce0152b8f]];
        vk.ic = new uint256[2][](3);
        vk.ic[0] = [uint256(0x279373d2bf019c92fe7f27b18aad265ca6767a1c1a8ce0b6c2d69dc3b4945e83), 0x2078bbd683c35630ae17e41ee231ed1e17374d795cf36ad6a7fd6f5d29a27056];
        vk.ic[1] = [uint256(0x27300964c6b9b9d3f502aa69fdbbe2578da0f4c6cd95dd9aac0b259af2bf2fe0), 0x1ceabf52ba10dd734123a779fda4f862e6f11828aff6b5cae8e123d6a081216b];
        vk.ic[2] = [uint256(0x12d48c39e9258b5147d423925f6f8816240169563e577385d27f4fc0f05348bc), 0x1844f2507a74d979d078a8f0cd89790c2a35e1a2111cf671d8308a071399c01d];
    }

    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input)
    {
        a = [uint256(0x3043455557301d2acc1d6209ef337757ad392339e796be4d4e3c6382826ddb67), 0x2dddc638e7becda00f2a384ac91a6986ae152a0f1c3b33740d2c5927b3af23e3];
        b = [[uint256(0x16d5103dc8b96f8d2655878bc836933a82822f44b9ae816fe25601cfb48d132d), 0x0951bd8390acedba56dc82a7438f074dd3c3463cc3041ae7ba62acdb2a70ea47], [uint256(0x266b9c07d94780de129c7e2a3db3ec83a45617824f3f7fd84d83a8ba92241eeb), 0x2dd7849805e81027e9cd052bc2c2bf36bd477cb5a9c8ef46f3ef1e96ca97c452]];
        c = [uint256(0x04df4ed6ae7c264fd18b740bfd57cc703281187568496df5650b9d607edfee46), 0x2e08c25f70dcc4293297ac61efe20c6164d1f21f2df3328a9df6dc1c242e27d1];
        input = new uint256[](2);
        input[0] = 0x000000000000000000000000000000000000000000000000000000000016cfd8;
        input[1] = 0x194dc92a4a1d8b58b2797776e1da7ea8913eb735a0984685476c4ae0e672f734;
    }
}
