//! Export a real proof + verifying key + public inputs into a Foundry test that verifies them on the
//! EVM (BN254 precompiles). Groth16/BN254 uses the same EIP-197 encoding as Solana's alt_bn128, so the
//! same proof verifies on Ethereum. Run on a Mini (from the repo root):
//!   cargo run --release --bin evm_export
//! then in evm/:  forge test -vv

use ark_bn254::{Bn254, Fq, Fr, G1Affine, G2Affine};
use ark_ff::{BigInteger, PrimeField};
use ark_groth16::{Proof, VerifyingKey};
use credit_solvency_core::circuit::prove_solvency;
use std::fs;

fn hex32(bytes: &[u8]) -> String {
    let mut o = [0u8; 32];
    o[32 - bytes.len()..].copy_from_slice(bytes);
    let mut s = String::from("0x");
    for b in o {
        s.push_str(&format!("{b:02x}"));
    }
    s
}
fn fq(x: &Fq) -> String {
    hex32(&x.into_bigint().to_bytes_be())
}
fn fr(x: &Fr) -> String {
    hex32(&x.into_bigint().to_bytes_be())
}
fn g1(p: &G1Affine) -> (String, String) {
    (fq(&p.x), fq(&p.y))
}
// EIP-197 order: imaginary (c1) first, then real (c0).
fn g2(p: &G2Affine) -> (String, String, String, String) {
    (fq(&p.x.c1), fq(&p.x.c0), fq(&p.y.c1), fq(&p.y.c0))
}

fn main() {
    let n = 10usize;
    let collateral: Vec<u128> = (0..n as u128).map(|i| 150_000 + i * 1_000).collect();
    let performing = vec![true; n];
    let kyc = vec![true; n];
    let total: u128 = collateral.iter().sum();
    let threshold = total - 50_000;

    let (vk, proof, public): (VerifyingKey<Bn254>, Proof<Bn254>, Vec<Fr>) =
        prove_solvency(&collateral, &performing, &kyc, threshold);

    let (ax, ay) = g1(&proof.a);
    let (bx1, bx0, by1, by0) = g2(&proof.b);
    let (cx, cy) = g1(&proof.c);
    let (alx, aly) = g1(&vk.alpha_g1);
    let (bex1, bex0, bey1, bey0) = g2(&vk.beta_g2);
    let (gx1, gx0, gy1, gy0) = g2(&vk.gamma_g2);
    let (dx1, dx0, dy1, dy0) = g2(&vk.delta_g2);

    let mut ic = String::new();
    for (i, p) in vk.gamma_abc_g1.iter().enumerate() {
        let (x, y) = g1(p);
        ic.push_str(&format!("        vk.ic[{i}] = [uint256({x}), {y}];\n"));
    }
    let mut inputs = String::new();
    for (i, s) in public.iter().enumerate() {
        inputs.push_str(&format!("        input[{i}] = {};\n", fr(s)));
    }

    let sol = format!(
        r#"// SPDX-License-Identifier: MIT
// GENERATED by `cargo run --bin evm_export` from a real proof. Do not edit by hand.
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "../src/Verifier.sol";

contract VerifierTest is Test {{
    function _vk() internal pure returns (Verifier.VK memory vk) {{
        vk.alpha = [uint256({alx}), {aly}];
        vk.beta = [[uint256({bex1}), {bex0}], [uint256({bey1}), {bey0}]];
        vk.gamma = [[uint256({gx1}), {gx0}], [uint256({gy1}), {gy0}]];
        vk.delta = [[uint256({dx1}), {dx0}], [uint256({dy1}), {dy0}]];
        vk.ic = new uint256[2][]({nic});
{ic}    }}

    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input)
    {{
        a = [uint256({ax}), {ay}];
        b = [[uint256({bx1}), {bx0}], [uint256({by1}), {by0}]];
        c = [uint256({cx}), {cy}];
        input = new uint256[]({ninput});
{inputs}    }}

    function testVerifiesRealProofOnEVM() public view {{
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input) = _proof();
        bool ok = Verifier.verify(a, b, c, input, _vk());
        assertTrue(ok, "real proof failed to verify on the EVM");
    }}

    function testGas() public {{
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input) = _proof();
        Verifier.VK memory vk = _vk();
        uint256 g = gasleft();
        bool ok = Verifier.verify(a, b, c, input, vk);
        uint256 used = g - gasleft();
        emit log_named_uint("EVM verification gas", used);
        assertTrue(ok, "verify failed");
    }}

    function testRejectsAlteredPublicInput() public view {{
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input) = _proof();
        input[0] = input[0] + 1; // tamper with a public input
        bool ok = Verifier.verify(a, b, c, input, _vk());
        assertFalse(ok, "altered public input must not verify");
    }}
}}
"#,
        nic = vk.gamma_abc_g1.len(),
        ninput = public.len(),
    );

    // A deployable contract that verifies the baked-in real proof on-chain and emits the result,
    // so a single tx on a public network (e.g. Sepolia) proves the verification works end to end.
    let demo = format!(
        r#"// SPDX-License-Identifier: MIT
// GENERATED by `cargo run --bin evm_export` from a real proof. Do not edit by hand.
pragma solidity ^0.8.20;

import "./Verifier.sol";

contract SolvencyVerifierDemo {{
    event Verified(bool ok, uint256 gasUsed);

    // Verify the baked-in real proof on-chain; emits Verified(true, gas). No arguments.
    function verify() external returns (bool ok) {{
        Verifier.VK memory vk = _vk();
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input) = _proof();
        uint256 g = gasleft();
        ok = Verifier.verify(a, b, c, input, vk);
        emit Verified(ok, g - gasleft());
    }}

    function _vk() internal pure returns (Verifier.VK memory vk) {{
        vk.alpha = [uint256({alx}), {aly}];
        vk.beta = [[uint256({bex1}), {bex0}], [uint256({bey1}), {bey0}]];
        vk.gamma = [[uint256({gx1}), {gx0}], [uint256({gy1}), {gy0}]];
        vk.delta = [[uint256({dx1}), {dx0}], [uint256({dy1}), {dy0}]];
        vk.ic = new uint256[2][]({nic});
{ic}    }}

    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[] memory input)
    {{
        a = [uint256({ax}), {ay}];
        b = [[uint256({bx1}), {bx0}], [uint256({by1}), {by0}]];
        c = [uint256({cx}), {cy}];
        input = new uint256[]({ninput});
{inputs}    }}
}}
"#,
        nic = vk.gamma_abc_g1.len(),
        ninput = public.len(),
    );

    fs::create_dir_all("evm/test").expect("mkdir evm/test");
    fs::write("evm/test/Verifier.t.sol", sol).expect("write test");
    fs::write("evm/src/SolvencyVerifierDemo.sol", demo).expect("write demo");
    println!("wrote evm/test/Verifier.t.sol and evm/src/SolvencyVerifierDemo.sol");
    println!("({} public inputs, {} IC points)", public.len(), vk.gamma_abc_g1.len());
}
